### ISSUE TITLE
parameter values for inference

### ISSUE THREAD

**Issue by santhosh-sp** [coqui-ai/xtts-streaming-server#8]
Hello,

What are the exact parameter values need to pass. 1. speaker embedding and 2.gpt_conda_latent

![image](https://github.com/coqui-ai/xtts-streaming-server/assets/107021850/eb0a2f56-838b-4cc7-874f-5ddc5744787b)

Thanks,
santhosh

**Comment by abeiro** [comment]
the ones you obtain as the result of cloning a voice

**Comment by WeberJulian** [comment]
Hey, you have an exhaustive example of how to call the endpoints here: https://github.com/coqui-ai/xtts-streaming-server/blob/main/test/test_streaming.py

**Comment by santhosh-sp** [comment]
> the ones you obtain as the result of cloning a voice

Hi @abeiro, 

I tried with below payload and I got the response from postman. Unfortunately the audio is not playing anything. 

[tts_payload.json](https://github.com/coqui-ai/xtts-streaming-server/files/13559591/tts_payload.json)


![image](https://github.com/coqui-ai/xtts-streaming-server/assets/107021850/41efea96-cfb2-494a-bf1f-2157a622f461)

Even its not playing in swagger API.

Please check and revert me.

Thanks in advance,
Santhosh.

**Comment by WeberJulian** [comment]
I think your calling the endpoint correctly hence the status code, it's just that you don't interpret the response correctly. Here is some python code to interpret the audio checks: https://github.com/coqui-ai/xtts-streaming-server/blob/main/test/test_streaming.py

If you want the JS equivalent, there is the webapp on this repo.

**Comment by santhosh-sp** [comment]
Its working for first time and getting below error.

    | RuntimeError: CUDA error: device-side assert triggered
    | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by WeberJulian** [comment]
It's quite a general error, but probably because you ran multiple concurrent requests right?

**Comment by santhosh-sp** [comment]
Yes, I am using multiple requests. Is there any way to handle multiple requests for TTS streaming?

I am using 3 * 24 GB VRAM RTX 3090. 

Please suggest an approach to handle this problem....

Some times getting this error when request from UI. 
Error:

| RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by reuben** [comment]
You need to run multiple servers and distribute requests to them in a way that doesn't send two concurrent requests to the same server.

**Comment by santhosh-sp** [comment]
Could you share  the capability of max concurrent requests on single 24 GPU?. If not what are limitations for scalable application?

**Comment by santhosh-sp** [comment]
Thanks for the update. @reuben
